#!/bin/bash
set -euo pipefail

if [ -z "${BASH_SOURCE+x}" ]; then
  echo "Error: this script must be run with bash" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

case "$SCRIPT_DIR" in
  *\ *)
    echo "Error: path contains spaces — FPC does not support spaces in unit paths" >&2
    echo "  $SCRIPT_DIR" >&2
    exit 1
    ;;
esac

CFG_FILE="$SCRIPT_DIR/fafafa_tui.cfg"

cat > "$CFG_FILE" <<EOF
# fafafa.tui compiler config — generated by install.sh
# Usage: fpc @fafafa_tui.cfg yourapp.lpr
-MObjFPC
-Sh
-Fu${SCRIPT_DIR}/src/core
-Fu${SCRIPT_DIR}/src/text
-Fu${SCRIPT_DIR}/src/layout
-Fu${SCRIPT_DIR}/src/widgets
-Fu${SCRIPT_DIR}/src/backend
-Fu${SCRIPT_DIR}/src/terminal
-Fu${SCRIPT_DIR}/src/input
-Fu${SCRIPT_DIR}/src/app
-Fu${SCRIPT_DIR}/src/platform
EOF

echo "Generated: $CFG_FILE"
echo ""
echo "Usage:"
echo "  fpc @${CFG_FILE} yourapp.lpr"
echo ""
echo "Or include fafafa_tui.mk in your Makefile:"
echo "  FTUI_ROOT := ${SCRIPT_DIR}"
echo "  include \$(FTUI_ROOT)/fafafa_tui.mk"
