program test_runner;

// Master test runner. Each tests/test_<unit>.pas registers its tests
// here; we then dispatch to ftui_testkit.RunAllTests.
//
// Add new test units to both the `uses` and the registration block.

{$mode objfpc}{$H+}

uses
  SysUtils,
  ftui_testkit,
  test_rect,
  test_color,
  test_modifier,
  test_style,
  test_cell,
  test_buffer,
  test_bytes,
  test_ansi,
  test_ansi_backend,
  test_text,
  test_layout,
  test_test_backend,
  test_clear,
  test_block,
  test_paragraph,
  test_list,
  test_input_parser,
  test_terminal_smoke,
  test_grapheme,
  test_input_editor,
  test_interaction,
  test_overlay,
  test_scrollbar,
  test_terminal_contract,
  test_cli888_scenarios,
  test_focus,
  test_color_cap,
  test_gauge,
  test_tabs,
  test_table,
  test_tree,
  test_form,
  test_sparkline,
  test_canvas,
  test_dialog,
  test_frame_budget,
  test_event_loop,
  test_clipboard,
  test_layout_dsl,
  test_split_pane,
  test_theme,
  test_anim,
  test_menu,
  test_statusbar,
  test_toast,
  test_textarea,
  test_barchart,
  test_linechart,
  test_input,
  test_scrollview,
  test_calendar,
  test_progress_group,
  test_grid,
  test_image,
  test_virtual_list,
  test_syntax,
  test_markdown,
  test_command_palette,
  test_tooltip,
  test_file_tree,
  test_keybind,
  test_breadcrumb,
  test_timeline,
  test_kanban,
  test_diffview,
  test_notification_center,
  test_app,
  test_screen,
  test_popover,
  test_select,
  test_modal,
  test_format;

var
  Failed: Integer;
begin
  RegisterRectTests;
  RegisterColorTests;
  RegisterModifierTests;
  RegisterStyleTests;
  RegisterCellTests;
  RegisterBufferTests;
  RegisterBytesTests;
  RegisterAnsiTests;
  RegisterAnsiBackendTests;
  RegisterTextTests;
  RegisterLayoutTests;
  RegisterTestBackendTests;
  RegisterClearTests;
  RegisterBlockTests;
  RegisterParagraphTests;
  RegisterListTests;
  RegisterInputParserTests;
  RegisterTerminalSmokeTests;
  RegisterGraphemeTests;
  RegisterInputEditorTests;
  RegisterInteractionTests;
  RegisterOverlayTests;
  RegisterScrollbarTests;
  RegisterTerminalContractTests;
  RegisterCli888ScenarioTests;
  RegisterFocusTests;
  RegisterColorCapTests;
  RegisterGaugeTests;
  RegisterTabsTests;
  RegisterTableTests;
  RegisterTreeTests;
  RegisterFormTests;
  RegisterSparklineTests;
  RegisterCanvasTests;
  RegisterDialogTests;
  RegisterFrameBudgetTests;
  RegisterEventLoopTests;
  RegisterClipboardTests;
  RegisterLayoutDslTests;
  RegisterSplitPaneTests;
  RegisterThemeTests;
  RegisterAnimTests;
  RegisterMenuTests;
  RegisterStatusBarTests;
  RegisterToastTests;
  RegisterTextAreaTests;
  RegisterBarChartTests;
  RegisterLineChartTests;
  RegisterInputTests;
  RegisterScrollViewTests;
  RegisterCalendarTests;
  RegisterProgressGroupTests;
  RegisterGridTests;
  RegisterImageTests;
  RegisterVirtualListTests;
  RegisterSyntaxTests;
  RegisterMarkdownTests;
  RegisterCommandPaletteTests;
  RegisterTooltipTests;
  RegisterFileTreeTests;
  RegisterKeybindTests;
  RegisterBreadcrumbTests;
  RegisterTimelineTests;
  RegisterKanbanTests;
  RegisterDiffViewTests;
  RegisterNotificationCenterTests;
  test_app.RegisterTests;
  test_screen.RegisterTests;
  test_popover.RegisterTests;
  test_select.RegisterTests;
  test_modal.RegisterTests;
  RegisterFormatTests;
  Failed := RunAllTests;
  if Failed = 0 then
    Halt(0)
  else
    Halt(1);
end.
